server:
  port: 9999 # 配置订单服务端口号

spring:
  application:
    name: @pom.artifactId@ # 配置订单服务id

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/ # 配置注册中心地址
    register-with-eureka: true # 向注册中心注册自己
    fetch-registry: false # 关闭发现注册服务